version: "3.9"
services:

  strades-scrapper:
    build: .
    env_file:
      - 'backend/.env'
    volumes:
      - .:/app
    depends_on:
      - postgres-service
      - redis-service
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  postgres-service:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordpostgres
      POSTGRES_DB: financedatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis-service:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
